//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSOAP.FinanceiroWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FinanceiroWS.FinanceiroServiceSoap")]
    public interface FinanceiroServiceSoap {
        
        // CODEGEN: Generating message contract since element name dataInicio from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustoTotalPeriodo", ReplyAction="*")]
        ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoResponse GetCustoTotalPeriodo(ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustoTotalPeriodo", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoResponse> GetCustoTotalPeriodoAsync(ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustoTotalPeriodoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustoTotalPeriodo", Namespace="http://tempuri.org/", Order=0)]
        public ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoRequestBody Body;
        
        public GetCustoTotalPeriodoRequest() {
        }
        
        public GetCustoTotalPeriodoRequest(ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustoTotalPeriodoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dataInicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string horaInicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string dataFim;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string horaFim;
        
        public GetCustoTotalPeriodoRequestBody() {
        }
        
        public GetCustoTotalPeriodoRequestBody(string dataInicio, string horaInicio, string dataFim, string horaFim) {
            this.dataInicio = dataInicio;
            this.horaInicio = horaInicio;
            this.dataFim = dataFim;
            this.horaFim = horaFim;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustoTotalPeriodoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustoTotalPeriodoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoResponseBody Body;
        
        public GetCustoTotalPeriodoResponse() {
        }
        
        public GetCustoTotalPeriodoResponse(ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustoTotalPeriodoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal GetCustoTotalPeriodoResult;
        
        public GetCustoTotalPeriodoResponseBody() {
        }
        
        public GetCustoTotalPeriodoResponseBody(decimal GetCustoTotalPeriodoResult) {
            this.GetCustoTotalPeriodoResult = GetCustoTotalPeriodoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FinanceiroServiceSoapChannel : ClienteSOAP.FinanceiroWS.FinanceiroServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinanceiroServiceSoapClient : System.ServiceModel.ClientBase<ClienteSOAP.FinanceiroWS.FinanceiroServiceSoap>, ClienteSOAP.FinanceiroWS.FinanceiroServiceSoap {
        
        public FinanceiroServiceSoapClient() {
        }
        
        public FinanceiroServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinanceiroServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanceiroServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanceiroServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoResponse ClienteSOAP.FinanceiroWS.FinanceiroServiceSoap.GetCustoTotalPeriodo(ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoRequest request) {
            return base.Channel.GetCustoTotalPeriodo(request);
        }
        
        public decimal GetCustoTotalPeriodo(string dataInicio, string horaInicio, string dataFim, string horaFim) {
            ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoRequest inValue = new ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoRequest();
            inValue.Body = new ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoRequestBody();
            inValue.Body.dataInicio = dataInicio;
            inValue.Body.horaInicio = horaInicio;
            inValue.Body.dataFim = dataFim;
            inValue.Body.horaFim = horaFim;
            ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoResponse retVal = ((ClienteSOAP.FinanceiroWS.FinanceiroServiceSoap)(this)).GetCustoTotalPeriodo(inValue);
            return retVal.Body.GetCustoTotalPeriodoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoResponse> ClienteSOAP.FinanceiroWS.FinanceiroServiceSoap.GetCustoTotalPeriodoAsync(ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoRequest request) {
            return base.Channel.GetCustoTotalPeriodoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoResponse> GetCustoTotalPeriodoAsync(string dataInicio, string horaInicio, string dataFim, string horaFim) {
            ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoRequest inValue = new ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoRequest();
            inValue.Body = new ClienteSOAP.FinanceiroWS.GetCustoTotalPeriodoRequestBody();
            inValue.Body.dataInicio = dataInicio;
            inValue.Body.horaInicio = horaInicio;
            inValue.Body.dataFim = dataFim;
            inValue.Body.horaFim = horaFim;
            return ((ClienteSOAP.FinanceiroWS.FinanceiroServiceSoap)(this)).GetCustoTotalPeriodoAsync(inValue);
        }
    }
}
